### ISSUE TITLE
Feedback on lesson 2

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/intro_to_automation#1]
There are a couple of things in lesson 2 that I think might be worth looking at:

- It states that the standard project metadata descriptions are in PEP 518, but this only argued that a TOML file should be used and specified what the `[build-system]` bit should look like. PEP 621 specified the `[project]` bits.
- The bonus section recommending to use `setuptools-scm` might result in some students going down a rabbit hole that takes up too much time. The tutorial for `setuptools-scm` is pretty good nowadays, but it'll involve adding a `[build-system]` to their `pyproject.toml` without a formal introduction to what this is, switching to dynamic versioning, adding a tool heading, and editing their `__init__.py` to set the package version only if the `_version.py` file has been generated. It's nothing too difficult if you've done it before, but for somebody who's new to this there's a lot of jargon and magic commands involved. Maybe it could just be marked as 'advanced' or something?
- It could use some details at the end describing how, after adding scripting entrypoints, their code should be run via the plain command line script `miller` rather than using `python3 miller` or something.
    - I'm not sure if it might also be worth adding a `__main__.py` containing `from . import main; main()` so they can do `python3 -m miller`, as having a `__main__.py`, an `if __name__ == "__main__.py"` section, and a scripting entrypoint might be a bit much.

**Comment by ZedThree** [comment]
Fixed most of these issues
